CREATE TABLE IF NOT EXISTS folders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  folder_id INTEGER NOT NULL,
  imgbb_url TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS system_stats (
  key TEXT PRIMARY KEY,
  value INTEGER DEFAULT 0,
  last_reset DATE DEFAULT (CURRENT_DATE)
);

INSERT OR IGNORE INTO system_stats (key, value, last_reset) VALUES ('daily_requests', 0, CURRENT_DATE);
